import type { Booking, ClosetItem, Creator, DesignerPiece, Post, Review, Service } from "./types";
import type { ProductEntitlement, Purchase, TasteProduct, TasteProductItem, TasteProductOutfit } from "./types/commerce";

const mediaMap: Record<string, string> = {
  "photo-1524504388940-b1c1722653e1": "bytaste-media-01.jpg",
  "photo-1515886657613-9f3515b0c78f": "bytaste-media-03.jpg",
  "photo-1494790108377-be9c29b29330": "bytaste-media-07.jpg",
  "photo-1529139574466-a303027c1d8b": "bytaste-media-08.jpg",
  "photo-1531123897727-8f129e1688ce": "bytaste-media-10.jpg",
  "photo-1496747611176-843222e1e57c": "bytaste-media-13.jpg",
  "photo-1534528741775-53994a69daeb": "bytaste-media-15.jpg",
  "photo-1503342217505-b0a15ec3261c": "bytaste-media-14.jpg",
  "photo-1516762689617-e1cffcef479d": "bytaste-media-02.jpg",
  "photo-1485968579580-b6d095142e6e": "bytaste-media-16.jpg",
  "photo-1523398002811-999ca8dec234": "bytaste-media-09.jpg",
  "photo-1487412720507-e7ab37603c6f": "bytaste-media-11.jpg",
  "photo-1512436991641-6745cdb1723f": "bytaste-media-12.jpg",
  "photo-1542291026-7eec264c27ff": "bytaste-media-06.jpg",
  "photo-1506629905607-d9c297d1461d": "bytaste-media-04.jpg",
  "photo-1542060748-10c28b62716f": "bytaste-media-05.jpg",
  "photo-1543163521-1bf539c55dd2": "bytaste-media-06.jpg",
  "photo-1551488831-00ddcb6c6bd3": "bytaste-media-14.jpg",
};

const image = (id: string, _width = 1200) => `/assets/media/${mediaMap[id] ?? "bytaste-media-01.jpg"}`;

const fashionServices: Service[] = [
  {
    id: "quick-take",
    title: "Quick Take",
    shortTitle: "Quick Take",
    price: 25,
    priceLabel: "$25",
    turnaround: "24h",
    summary: "One styling question answered with a short voice or video-style note.",
    deliverables: ["90-second creator note", "One outfit or purchase call", "One revision"],
    intakePrompts: ["What decision do you need help with?", "Where will you wear it?"],
    addOns: ["Rush reply", "Second option"],
    whoFor: ["Fast purchase decisions", "One event outfit", "Followers who already trust the creator's eye"],
    effortNote: "Best with 1-3 photos and a short decision prompt.",
  },
  {
    id: "style-diagnosis",
    title: "Style Diagnosis",
    shortTitle: "Diagnosis",
    price: 65,
    priceLabel: "$65",
    turnaround: "2 days",
    summary: "A clear read on your current aesthetic, palette, silhouettes, and next direction.",
    deliverables: ["Written style read", "Reference board", "Palette and silhouette notes", "One revision"],
    intakePrompts: ["What feels off about your style right now?", "Which references feel closest?"],
    addOns: ["Voice walkthrough", "Occasion capsule"],
    whoFor: ["Style resets", "Aesthetic transitions", "People who want a sharper repeatable direction"],
    effortNote: "Best with a few current outfits and 2-3 reference images.",
  },
  {
    id: "wardrobe-audit",
    title: "Wardrobe Audit",
    shortTitle: "Audit",
    price: 115,
    priceLabel: "$115",
    turnaround: "3-5 days",
    summary: "Upload your closet and get keep, donate, repair calls plus outfits from what you own.",
    deliverables: ["Tagged closet inventory", "Keep, donate, repair calls", "8-12 styled outfits", "Voice walkthrough"],
    intakePrompts: ["What do you want your wardrobe to do better?", "Which pieces are hardest to wear?"],
    addOns: ["Rush delivery", "Extra 5 outfits", "Shopping gap list"],
    whoFor: ["Closet cleanups", "No-buy months", "People with good pieces that are hard to combine"],
    effortNote: "Best with clear photos of the pieces you actually wear.",
  },
  {
    id: "capsule-build",
    title: "Capsule Build",
    shortTitle: "Capsule",
    price: 165,
    priceLabel: "$165",
    turnaround: "5 days",
    summary: "A focused shopping edit for a season, trip, or aesthetic shift with budget tiers.",
    deliverables: ["8-15 linked pieces", "Budget tier guidance", "Fit and styling notes", "Affiliate-ready shopping list"],
    intakePrompts: ["What is the capsule for?", "What total budget should the edit respect?"],
    addOns: ["Plus-size alternatives", "Sustainable-only edit", "Designer piece integration"],
    whoFor: ["Seasonal capsules", "Travel wardrobes", "Followers ready to buy with a clear budget"],
    effortNote: "Best with your budget, sizes, no-go brands, and two references.",
  },
];

export const creators: Creator[] = [
  {
    id: "creator-amara",
    handle: "amara-okafor",
    displayName: "Amara Okafor",
    location: "Lagos and London",
    avatar: image("photo-1524504388940-b1c1722653e1", 500),
    cover: image("photo-1515886657613-9f3515b0c78f"),
    bio: "Soft minimalist wardrobes with practical polish and warm-weather tailoring.",
    verticals: ["Fashion"],
    aesthetics: ["soft minimalist", "tailoring", "warm neutrals", "workwear"],
    followerCount: 87000,
    rating: 4.96,
    reviewCount: 142,
    avgTurnaround: "2d",
    verified: true,
    rising: false,
    tasteSignature: "Warm minimalism with one precise statement.",
    tastePrinciples: ["Repeatable outfit formulas", "Soft structure before trend", "Buy fewer gaps, style harder"],
    storefrontHeadline: "Make your everyday wardrobe feel finished.",
    storefrontDescription:
      "Amara sells tight seasonal edits and calm one-to-one styling for followers who want polished outfits without overbuying.",
    primaryOfferType: "service",
    featuredProductId: "11111111-1111-4111-8111-111111111111",
    featuredServiceId: "quick-take",
    instagramUrl: "https://instagram.com/amara.styles",
    tiktokUrl: "https://tiktok.com/@amarafits",
    socialVerifiedAt: "2026-07-01",
    storefrontPublished: true,
    availability: "Taking 6 new bookings this week",
    services: fashionServices.map((service) =>
      service.id === "wardrobe-audit" ? { ...service, price: 95, priceLabel: "$95" } : service,
    ),
    socials: { instagram: "@amara.styles", tiktok: "@amarafits" },
  },
  {
    id: "creator-lena",
    handle: "lena-park",
    displayName: "Lena Park",
    location: "Seoul",
    avatar: image("photo-1494790108377-be9c29b29330", 500),
    cover: image("photo-1529139574466-a303027c1d8b"),
    bio: "Sharp city uniforms, modular layers, and capsule systems for small closets.",
    verticals: ["Fashion"],
    aesthetics: ["streetwear", "monochrome", "modular", "city"],
    followerCount: 34000,
    rating: 4.91,
    reviewCount: 67,
    avgTurnaround: "3d",
    verified: false,
    rising: true,
    tasteSignature: "Modular city layers that earn their space.",
    tastePrinciples: ["Weatherproof but intentional", "Small-closet systems", "Black, grey, denim, one tension point"],
    storefrontHeadline: "Build the city uniform you actually repeat.",
    storefrontDescription:
      "Lena turns creator trust into compact shopping edits and outfit systems for followers with small closets and busy weeks.",
    primaryOfferType: "edit",
    featuredProductId: "22222222-2222-4222-8222-222222222222",
    featuredServiceId: "capsule-build",
    instagramUrl: "https://instagram.com/lena.layers",
    socialVerifiedAt: "2026-06-22",
    storefrontPublished: true,
    availability: "Capsule slots reopen Friday",
    services: fashionServices.map((service) =>
      service.id === "capsule-build" ? { ...service, price: 145, priceLabel: "$145" } : service,
    ),
    socials: { instagram: "@lena.layers" },
  },
  {
    id: "creator-noor",
    handle: "noor-hassan",
    displayName: "Noor Hassan",
    location: "Toronto",
    avatar: image("photo-1531123897727-8f129e1688ce", 500),
    cover: image("photo-1496747611176-843222e1e57c"),
    bio: "Modest occasionwear, elegant proportions, and color stories that photograph beautifully.",
    verticals: ["Fashion"],
    aesthetics: ["modest", "occasionwear", "romantic", "color"],
    followerCount: 52000,
    rating: 4.93,
    reviewCount: 88,
    avgTurnaround: "2d",
    verified: true,
    rising: false,
    tasteSignature: "Elegant coverage, saturated color, camera-ready proportions.",
    tastePrinciples: ["Modesty without flattening shape", "One color story per event", "Accessories set the formality"],
    storefrontHeadline: "Occasionwear that photographs beautifully and still feels like you.",
    storefrontDescription:
      "Noor packages her event styling taste into wedding-guest edits and personal look selection for modest dressers.",
    primaryOfferType: "service",
    featuredProductId: "33333333-3333-4333-8333-333333333333",
    featuredServiceId: "quick-take",
    instagramUrl: "https://instagram.com/noor.edits",
    tiktokUrl: "https://tiktok.com/@noorwears",
    socialVerifiedAt: "2026-06-28",
    storefrontPublished: true,
    availability: "Event edits available in 48h",
    services: fashionServices,
    socials: { instagram: "@noor.edits", tiktok: "@noorwears" },
  },
  {
    id: "creator-ivy",
    handle: "ivy-marlowe",
    displayName: "Ivy Marlowe",
    location: "New York",
    avatar: image("photo-1534528741775-53994a69daeb", 500),
    cover: image("photo-1503342217505-b0a15ec3261c"),
    bio: "Dark academia, thrifted tailoring, and designer drops for people who love texture.",
    verticals: ["Fashion", "Design"],
    aesthetics: ["dark academia", "vintage", "texture", "designer"],
    followerCount: 18000,
    rating: 4.88,
    reviewCount: 31,
    avgTurnaround: "4d",
    verified: false,
    rising: true,
    tasteSignature: "Texture-led vintage with a designer eye.",
    tastePrinciples: ["Material first", "Repairable flaws are opportunity", "Academic shapes, modern fit"],
    storefrontHeadline: "Find the secondhand pieces worth building around.",
    storefrontDescription:
      "Ivy monetises a sharp archive eye through weekly vintage edits, texture guides, and slow-fashion styling.",
    primaryOfferType: "edit",
    featuredProductId: "44444444-4444-4444-8444-444444444444",
    featuredServiceId: "style-diagnosis",
    instagramUrl: "https://instagram.com/ivymakes",
    storefrontPublished: true,
    availability: "Weekly vintage edit drops Monday",
    services: fashionServices.filter((service) => service.id !== "quick-take"),
    socials: { instagram: "@ivymakes" },
  },
];

export const tasteProducts: TasteProduct[] = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    creatorId: "creator-amara",
    creatorHandle: "amara-okafor",
    slug: "copenhagen-2027-edit",
    title: "Copenhagen 2027 Edit",
    subtitle: "Twenty warm-minimal pieces I would actually buy now.",
    description:
      "A paid seasonal taste product for followers who want Amara's buying eye without booking a full wardrobe audit.",
    coverImageUrl: image("photo-1515886657613-9f3515b0c78f"),
    previewText:
      "The edit is built around soft tailoring, controlled texture, and pieces that can move from office to travel.",
    previewItemCount: 4,
    totalItemCount: 20,
    outfitCount: 6,
    priceCents: 1900,
    currency: "usd",
    status: "published",
    accessType: "paid",
    affiliateDisclosure: "Some shopping links may be affiliate links. Amara's notes stay independent of commission.",
    publishedAt: "2026-07-08",
    updatedAt: "2026-07-11",
    whoIsItFor: ["Warm minimalists", "Office-to-weekend wardrobes", "Followers who want fewer, stronger buys"],
    theme: "Soft tailoring / warm neutrals / polished travel",
  },
  {
    id: "22222222-2222-4222-8222-222222222222",
    creatorId: "creator-lena",
    creatorHandle: "lena-park",
    slug: "rainy-city-capsule",
    title: "Rainy City Capsule",
    subtitle: "A compact weatherproof edit for small closets.",
    description:
      "Lena's one-to-many shopping list for followers who want city layers that look intentional, not tactical.",
    coverImageUrl: image("photo-1523398002811-999ca8dec234"),
    previewText: "Start with one technical shell, one clean trouser, and one bag that can handle weather.",
    previewItemCount: 3,
    totalItemCount: 15,
    outfitCount: 5,
    priceCents: 1500,
    currency: "usd",
    status: "published",
    accessType: "paid",
    affiliateDisclosure: "Contains affiliate shopping links where available.",
    publishedAt: "2026-07-06",
    updatedAt: "2026-07-10",
    whoIsItFor: ["Commuters", "Small closets", "Monochrome dressers"],
    theme: "Weatherproof city uniform",
  },
  {
    id: "33333333-3333-4333-8333-333333333333",
    creatorId: "creator-noor",
    creatorHandle: "noor-hassan",
    slug: "wedding-guest-under-200",
    title: "Wedding Guest Dresses Under $200",
    subtitle: "Modest, camera-ready options with accessory formulas.",
    description:
      "Noor's paid edit for followers who need event polish fast and want a clear read on fit, color, and formality.",
    coverImageUrl: image("photo-1487412720507-e7ab37603c6f"),
    previewText: "The strongest low-stress guest looks usually need one saturated color and one metallic tension point.",
    previewItemCount: 4,
    totalItemCount: 18,
    outfitCount: 7,
    priceCents: 1700,
    currency: "usd",
    status: "published",
    accessType: "paid",
    affiliateDisclosure: "Some product links may generate affiliate revenue.",
    publishedAt: "2026-07-03",
    updatedAt: "2026-07-09",
    whoIsItFor: ["Modest dressers", "Wedding guests", "Color-forward occasionwear"],
    theme: "Romantic event dressing",
  },
  {
    id: "44444444-4444-4444-8444-444444444444",
    creatorId: "creator-ivy",
    creatorHandle: "ivy-marlowe",
    slug: "vintage-listings-worth-buying",
    title: "Vintage Listings Worth Buying This Week",
    subtitle: "Texture, tailoring, and repairable finds before they disappear.",
    description:
      "A weekly paid edit that turns Ivy's archive eye into a fast shopping decision layer for followers.",
    coverImageUrl: image("photo-1512436991641-6745cdb1723f"),
    previewText: "This week is about wool texture, narrow collars, and suede accessories with fixable flaws.",
    previewItemCount: 3,
    totalItemCount: 12,
    outfitCount: 4,
    priceCents: 1200,
    currency: "usd",
    status: "published",
    accessType: "paid",
    affiliateDisclosure: "Listings may disappear quickly; some links may be affiliate links.",
    publishedAt: "2026-07-07",
    updatedAt: "2026-07-12",
    whoIsItFor: ["Vintage shoppers", "Dark academia wardrobes", "Texture-led buyers"],
    theme: "Secondhand texture hunt",
  },
];

export const tasteProductItems: TasteProductItem[] = [
  {
    id: "item-amara-preview-01",
    productId: "11111111-1111-4111-8111-111111111111",
    name: "Washed linen blazer",
    brand: "Arket",
    imageUrl: image("photo-1485968579580-b6d095142e6e"),
    priceLabel: "$189",
    creatorNote: "Preview: the shoulder is soft enough for travel but still gives the outfit a frame.",
    isPreview: true,
    verdict: "chosen",
    sortOrder: 1,
  },
  {
    id: "item-amara-preview-02",
    productId: "11111111-1111-4111-8111-111111111111",
    name: "Cream column tank",
    brand: "COS",
    imageUrl: image("photo-1542060748-10c28b62716f"),
    priceLabel: "$45",
    creatorNote: "Preview: use this as the quiet base under every stronger texture.",
    isPreview: true,
    verdict: "chosen",
    sortOrder: 2,
  },
  {
    id: "item-amara-locked-01",
    productId: "11111111-1111-4111-8111-111111111111",
    name: "Cognac city slingback",
    brand: "Independent seller",
    imageUrl: image("photo-1543163521-1bf539c55dd2"),
    destinationUrl: "https://example.com/cognac-city-slingback",
    priceLabel: "$128",
    creatorNote: "Full edit: this warms the entire palette and stops the neutral base from going flat.",
    isPreview: false,
    verdict: "chosen",
    sortOrder: 3,
  },
  {
    id: "item-amara-locked-02",
    productId: "11111111-1111-4111-8111-111111111111",
    name: "Structured raffia tote",
    brand: "Cuyana",
    imageUrl: image("photo-1542291026-7eec264c27ff"),
    destinationUrl: "https://example.com/structured-raffia-tote",
    priceLabel: "$268",
    creatorNote: "Full edit: the texture makes the office pieces feel summer-specific without becoming beachwear.",
    isPreview: false,
    verdict: "chosen",
    sortOrder: 4,
  },
  {
    id: "item-amara-rejected-01",
    productId: "11111111-1111-4111-8111-111111111111",
    name: "Cropped puffer",
    brand: "Trend rack",
    imageUrl: image("photo-1515886657613-9f3515b0c78f"),
    creatorNote: "Preview: skip it here. The cropped volume fights the long-line tailoring this edit is built around.",
    isPreview: true,
    verdict: "rejected",
    sortOrder: 5,
  },
  {
    id: "item-lena-preview-01",
    productId: "22222222-2222-4222-8222-222222222222",
    name: "Matte shell jacket",
    brand: "Rains",
    imageUrl: image("photo-1523398002811-999ca8dec234"),
    priceLabel: "$140",
    creatorNote: "Preview: matte finish keeps the technical layer from taking over the whole outfit.",
    isPreview: true,
    verdict: "chosen",
    sortOrder: 1,
  },
  {
    id: "item-lena-locked-01",
    productId: "22222222-2222-4222-8222-222222222222",
    name: "Nylon midi skirt",
    brand: "Weekday",
    imageUrl: image("photo-1529139574466-a303027c1d8b"),
    destinationUrl: "https://example.com/nylon-midi-skirt",
    priceLabel: "$69",
    creatorNote: "Full edit: gives the capsule motion while staying weather-safe.",
    isPreview: false,
    verdict: "chosen",
    sortOrder: 2,
  },
  {
    id: "item-noor-preview-01",
    productId: "33333333-3333-4333-8333-333333333333",
    name: "Long-sleeve satin dress",
    brand: "Aab",
    imageUrl: image("photo-1487412720507-e7ab37603c6f"),
    priceLabel: "$178",
    creatorNote: "Preview: the sleeve and drape give coverage without losing occasion softness.",
    isPreview: true,
    verdict: "chosen",
    sortOrder: 1,
  },
  {
    id: "item-noor-locked-01",
    productId: "33333333-3333-4333-8333-333333333333",
    name: "Metallic low mule",
    brand: "Reformation",
    imageUrl: image("photo-1543163521-1bf539c55dd2"),
    destinationUrl: "https://example.com/metallic-low-mule",
    priceLabel: "$168",
    creatorNote: "Full edit: a low metallic shoe raises formality while keeping the dress wearable.",
    isPreview: false,
    verdict: "chosen",
    sortOrder: 2,
  },
  {
    id: "item-ivy-preview-01",
    productId: "44444444-4444-4444-8444-444444444444",
    name: "Narrow-collar wool blazer",
    brand: "Vintage",
    imageUrl: image("photo-1512436991641-6745cdb1723f"),
    priceLabel: "$88",
    creatorNote: "Preview: inspect collar roll and lining first; this shape is worth tailoring.",
    isPreview: true,
    verdict: "chosen",
    sortOrder: 1,
  },
  {
    id: "item-ivy-locked-01",
    productId: "44444444-4444-4444-8444-444444444444",
    name: "Deadstock ribbon bag",
    brand: "Archive seller",
    imageUrl: image("photo-1542291026-7eec264c27ff"),
    destinationUrl: "https://example.com/deadstock-ribbon-bag",
    priceLabel: "$126",
    creatorNote: "Full edit: the trim reads intentional with wool, not costume, if the outfit stays otherwise matte.",
    isPreview: false,
    verdict: "chosen",
    sortOrder: 2,
  },
];

export const tasteProductOutfits: TasteProductOutfit[] = [
  {
    id: "outfit-amara-preview-01",
    productId: "11111111-1111-4111-8111-111111111111",
    title: "Arrival day tailoring",
    imageUrl: image("photo-1485968579580-b6d095142e6e"),
    creatorNote: "Preview outfit: blazer, column tank, and linen trouser. Keep accessories warm, not black.",
    itemIds: ["item-amara-preview-01", "item-amara-preview-02"],
    isPreview: true,
    sortOrder: 1,
  },
  {
    id: "outfit-amara-locked-01",
    productId: "11111111-1111-4111-8111-111111111111",
    title: "Office to dinner without changing clothes",
    imageUrl: image("photo-1516762689617-e1cffcef479d"),
    creatorNote: "Full edit: the shoe and tote do the evening work; do not add jewelry unless it is sculptural.",
    itemIds: ["item-amara-preview-02", "item-amara-locked-01", "item-amara-locked-02"],
    isPreview: false,
    sortOrder: 2,
  },
  {
    id: "outfit-lena-preview-01",
    productId: "22222222-2222-4222-8222-222222222222",
    title: "Rain commute, gallery after",
    imageUrl: image("photo-1523398002811-999ca8dec234"),
    creatorNote: "Preview outfit: keep the shell matte and the base column dark.",
    itemIds: ["item-lena-preview-01"],
    isPreview: true,
    sortOrder: 1,
  },
  {
    id: "outfit-noor-preview-01",
    productId: "33333333-3333-4333-8333-333333333333",
    title: "Garden ceremony",
    imageUrl: image("photo-1487412720507-e7ab37603c6f"),
    creatorNote: "Preview outfit: saturated dress, low metallic shoe, and one soft wrap.",
    itemIds: ["item-noor-preview-01"],
    isPreview: true,
    sortOrder: 1,
  },
  {
    id: "outfit-ivy-preview-01",
    productId: "44444444-4444-4444-8444-444444444444",
    title: "Library texture stack",
    imageUrl: image("photo-1512436991641-6745cdb1723f"),
    creatorNote: "Preview outfit: narrow wool over heavy cotton with one small decorative texture.",
    itemIds: ["item-ivy-preview-01"],
    isPreview: true,
    sortOrder: 1,
  },
];

export const purchaseSeed: Purchase[] = [
  {
    id: "purchase-demo-amara-copenhagen",
    customerId: "demo-customer",
    productId: "11111111-1111-4111-8111-111111111111",
    paymentStatus: "paid",
    amountCents: 1900,
    currency: "usd",
    purchasedAt: "2026-07-12",
  },
];

export const entitlementSeed: ProductEntitlement[] = [
  {
    id: "entitlement-demo-amara-copenhagen",
    customerId: "demo-customer",
    productId: "11111111-1111-4111-8111-111111111111",
    sourcePurchaseId: "purchase-demo-amara-copenhagen",
    grantedAt: "2026-07-12",
  },
];

export const posts: Post[] = [
  {
    id: "post-amara-01",
    creatorHandle: "amara-okafor",
    type: "transformation",
    title: "Maya's summer wardrobe reset",
    date: "2026-06-28",
    image: image("photo-1516762689617-e1cffcef479d"),
    summary: "A closet of almost-right basics became ten office-to-dinner looks.",
    body: "Maya had strong pieces, but every outfit felt unfinished. The fix was not more shopping. We built repeatable formulas around linen trousers, crisp tanks, one structured blazer, and two accent shoes.",
    tags: ["soft minimalist", "workwear", "transformation"],
    pinned: true,
    portfolio: true,
    taggedItems: [
      { name: "Cream linen trouser", brand: "Owned by customer" },
      { name: "Black column tank", brand: "COS" },
      { name: "Cognac slingback", brand: "Independent seller" },
    ],
  },
  {
    id: "post-amara-02",
    creatorHandle: "amara-okafor",
    type: "outfit",
    title: "The travel blazer formula",
    date: "2026-06-18",
    image: image("photo-1485968579580-b6d095142e6e"),
    summary: "A carry-on friendly outfit that still looks deliberate after a long flight.",
    body: "The blazer is soft enough to fold, the trouser does not crease badly, and the shoe is polished without asking too much of your feet.",
    tags: ["tailoring", "travel", "capsule"],
    portfolio: true,
    taggedItems: [
      { name: "Soft blazer", brand: "Arket", price: "$189" },
      { name: "Wide trouser", brand: "Uniqlo", price: "$49" },
      { name: "Leather tote", brand: "Cuyana", price: "$268" },
    ],
  },
  {
    id: "post-lena-01",
    creatorHandle: "lena-park",
    type: "moodboard",
    title: "Five-piece rainy city capsule",
    date: "2026-06-22",
    image: image("photo-1523398002811-999ca8dec234"),
    summary: "Weatherproof pieces that still feel precise, not tactical.",
    body: "The trick is choosing one technical layer, one clean trouser, and a bag that can handle weather without looking like hiking gear.",
    tags: ["streetwear", "monochrome", "city"],
    pinned: true,
    portfolio: true,
    taggedItems: [
      { name: "Shell jacket", brand: "Rains" },
      { name: "Nylon midi skirt", brand: "Weekday" },
      { name: "Chelsea boot", brand: "Vagabond" },
    ],
  },
  {
    id: "post-noor-01",
    creatorHandle: "noor-hassan",
    type: "outfit",
    title: "One dress, three wedding guest reads",
    date: "2026-06-20",
    image: image("photo-1487412720507-e7ab37603c6f"),
    summary: "A romantic base look adapted for garden, city hall, and evening receptions.",
    body: "The same dress can move across formality if the accessories shift the structure. I used metallic tension, a soft wrap, and one saturated bag.",
    tags: ["modest", "romantic", "occasionwear"],
    pinned: true,
    portfolio: true,
    taggedItems: [
      { name: "Long-sleeve satin dress", brand: "Aab" },
      { name: "Metallic mule", brand: "Reformation" },
      { name: "Silk wrap", brand: "Vintage" },
    ],
  },
  {
    id: "post-ivy-01",
    creatorHandle: "ivy-marlowe",
    type: "designer-drop",
    title: "Study Coat No. 02",
    date: "2026-06-12",
    image: image("photo-1512436991641-6745cdb1723f"),
    summary: "A cropped wool coat designed for layered autumn uniforms.",
    body: "This drop started from a thrifted men's coat and became a small run of cropped wool jackets with deep pockets and a narrow collar.",
    tags: ["dark academia", "designer", "vintage"],
    pinned: true,
    portfolio: true,
    taggedItems: [
      { name: "Study Coat No. 02", brand: "Ivy Marlowe Studio", price: "$340" },
      { name: "Pleated trouser", brand: "Vintage" },
    ],
  },
  {
    id: "post-ivy-02",
    creatorHandle: "ivy-marlowe",
    type: "article",
    title: "How to buy texture secondhand",
    date: "2026-05-30",
    image: image("photo-1515886657613-9f3515b0c78f"),
    summary: "A field guide for wool, suede, heavy cotton, and pieces worth repairing.",
    body: "Texture is what makes a small wardrobe feel rich. The best secondhand finds usually have one excellent material and one repairable flaw.",
    tags: ["vintage", "texture", "dark academia"],
    portfolio: false,
    taggedItems: [
      { name: "Wool blazer", brand: "Vintage" },
      { name: "Suede belt", brand: "Vintage" },
    ],
  },
];

export const designerPieces: DesignerPiece[] = [
  {
    id: "piece-ivy-01",
    creatorHandle: "ivy-marlowe",
    title: "Study Coat No. 02",
    image: image("photo-1512436991641-6745cdb1723f"),
    price: "$340",
    shopLabel: "Shop Ivy Studio",
    description: "Cropped wool outer layer with a narrow collar and reinforced pockets.",
  },
  {
    id: "piece-ivy-02",
    creatorHandle: "ivy-marlowe",
    title: "Archive Ribbon Bag",
    image: image("photo-1542291026-7eec264c27ff"),
    price: "$126",
    shopLabel: "View drop",
    description: "Small structured bag made from reclaimed ribbon trim and deadstock lining.",
  },
];

export const reviews: Review[] = [
  {
    id: "review-01",
    creatorHandle: "amara-okafor",
    customerName: "Maya R.",
    rating: 5,
    serviceTitle: "Wardrobe Audit",
    text: "Amara made my own clothes feel new. The voice notes were direct, kind, and easy to act on.",
  },
  {
    id: "review-02",
    creatorHandle: "noor-hassan",
    customerName: "Elena P.",
    rating: 5,
    serviceTitle: "Capsule Build",
    text: "Noor understood modest wedding guest styling better than anyone I found locally.",
  },
  {
    id: "review-03",
    creatorHandle: "lena-park",
    customerName: "Jules K.",
    rating: 5,
    serviceTitle: "Quick Take",
    text: "Fast, specific, and honestly saved me from buying the wrong coat.",
  },
];

export const closetSeed: ClosetItem[] = [
  {
    id: "closet-01",
    name: "Cream linen trouser",
    category: "Bottom",
    color: "Cream",
    image: image("photo-1506629905607-d9c297d1461d", 800),
    tags: ["linen", "workwear", "summer"],
    lastWorn: "2026-06-25",
  },
  {
    id: "closet-02",
    name: "Black column tank",
    category: "Top",
    color: "Black",
    image: image("photo-1542060748-10c28b62716f", 800),
    tags: ["basic", "layering"],
    lastWorn: "2026-06-29",
  },
  {
    id: "closet-03",
    name: "Cognac slingback",
    category: "Shoe",
    color: "Cognac",
    image: image("photo-1543163521-1bf539c55dd2", 800),
    tags: ["leather", "polished"],
    lastWorn: "2026-06-22",
  },
  {
    id: "closet-04",
    name: "Charcoal soft blazer",
    category: "Outerwear",
    color: "Charcoal",
    image: image("photo-1551488831-00ddcb6c6bd3", 800),
    tags: ["tailoring", "travel"],
    lastWorn: "2026-06-18",
  },
];

export const bookingSeed: Booking[] = [
  {
    id: "booking-2841",
    creatorHandle: "amara-okafor",
    serviceId: "wardrobe-audit",
    serviceTitle: "Wardrobe Audit",
    customerName: "Maya R.",
    price: 95,
    status: "ready",
    paymentStatus: "paid",
    createdAt: "2026-06-29",
    dueDate: "2026-07-04",
    brief: "Soft minimalist summer work wardrobe with fewer repeated panic outfits.",
    budget: "$400 gap budget",
    closetItemIds: ["closet-01", "closet-02", "closet-03", "closet-04"],
    deliverable: {
      title: "Maya's Summer Work Reset",
      voiceNoteLabel: "6 min creator walkthrough",
      outfits: [
        {
          id: "look-01",
          title: "Monday clean start",
          image: image("photo-1529139574466-a303027c1d8b"),
          notes: "Use the charcoal blazer as the structure and let the linen trouser keep it light.",
          items: ["Charcoal soft blazer", "Cream linen trouser", "Black column tank", "Cognac slingback"],
        },
        {
          id: "look-02",
          title: "Dinner after office",
          image: image("photo-1516762689617-e1cffcef479d"),
          notes: "Swap the blazer for a bare shoulder line and keep the cognac shoe for warmth.",
          items: ["Cream linen trouser", "Black column tank", "Cognac slingback"],
        },
      ],
    },
  },
];

export const aestheticTags = Array.from(new Set(creators.flatMap((creator) => creator.aesthetics))).sort();

export const getCreator = (handle: string) => creators.find((creator) => creator.handle === handle);

export const getService = (creatorHandle: string, serviceId: string) =>
  getCreator(creatorHandle)?.services.find((service) => service.id === serviceId);

export const getPost = (postId: string) => posts.find((post) => post.id === postId);

export const creatorPosts = (handle: string) => posts.filter((post) => post.creatorHandle === handle);

export const creatorPortfolio = (handle: string) =>
  posts.filter((post) => post.creatorHandle === handle && post.portfolio);

export const creatorReviews = (handle: string) => reviews.filter((review) => review.creatorHandle === handle);

export const creatorDesignerPieces = (handle: string) =>
  designerPieces.filter((piece) => piece.creatorHandle === handle);

export const creatorTasteProducts = (handle: string) =>
  tasteProducts.filter((product) => product.creatorHandle === handle && product.status === "published");

export const getTasteProduct = (creatorHandle: string, slug: string) =>
  tasteProducts.find((product) => product.creatorHandle === creatorHandle && product.slug === slug);

export const getTasteProductById = (productId: string) => tasteProducts.find((product) => product.id === productId);

export const tasteProductPreviewItems = (productId: string) =>
  tasteProductItems
    .filter((item) => item.productId === productId && item.isPreview)
    .sort((a, b) => a.sortOrder - b.sortOrder);

export const tasteProductFullItems = (productId: string) =>
  tasteProductItems.filter((item) => item.productId === productId).sort((a, b) => a.sortOrder - b.sortOrder);

export const tasteProductPreviewOutfits = (productId: string) =>
  tasteProductOutfits
    .filter((outfit) => outfit.productId === productId && outfit.isPreview)
    .sort((a, b) => a.sortOrder - b.sortOrder);

export const tasteProductFullOutfits = (productId: string) =>
  tasteProductOutfits.filter((outfit) => outfit.productId === productId).sort((a, b) => a.sortOrder - b.sortOrder);
